config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/appointements', to: 'pages#appointements', as: "appointements"  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointement.rb
class Appointement < ApplicationRecord
  belongs_to :user
  belongs_to :problem
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/models/problems_material.rb
class ProblemsMaterial < ApplicationRecord
  belongs_to :problem
  belongs_to :material
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
    class ApplicationController < ActionController::Base
      before_action :authenticate_user!
    end

app/controllers/appointements_controller.rb
class PagesController < ApplicationController
  def new

  end

  def create

  end

  def show

  end
end

app/controllers/pages_controller.rb
    class PagesController < ApplicationController
      skip_before_action :authenticate_user!, only: [:home]

      def home
      end

      def appointements

      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>TODO</title>
        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Satisfy&display=swap" rel="stylesheet">
        <%= csrf_meta_tags %>
        <%= action_cable_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
      </head>
      <body>
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>

        <%= yield %>

        <%= javascript_pack_tag 'application' %>
      </body>
    </html>

app/views/pages/appointements.html.erb
<!-- TASKS -->
<div id="title">
  <h1>Faites votre devis gratuitement</h1>
</div>
<div class="wrapper-tasks">
  <div class="row">
    <div class="col-sm">
      <h3>SANITAIRE</h3>
      <ul>
        <li>W.C au sol <input type="checkbox"></li>
        <li>W.C suspendu<input type="checkbox"></li>
        <li>Mitigeur lavabo et évier<input type="checkbox"></li>
        <li>Douche à l'italienne<input type="checkbox"></li>
        <li>Bac à douche<input type="checkbox"></li>
        <li>Paroi de douche<input type="checkbox"></li>
        <li>Faïence et Carrelage<input type="checkbox"></li>
        <li>Chauffe-eau électrique<input type="checkbox"></li>
        <li>Chauffe-eau plat<input type="checkbox"></li>
        <li>Pose d'adoucisseur ou d'aquabion<input type="checkbox"></li>
        <li><strong>Pose complète de sanitaire</strong><input type="checkbox"></li>
      </ul>
    </div>
    <div class="col-sm">
      <h3>CUISINE</h3>
      <ul>
        <li>Evier</li>
        <li>Plan de travail</li>
        <li>Hotte aspirante</li>
        <li>Pose de cuisine complète</li>
      </ul>
    </div>
    <div class="col-sm">
      <h3>CLIMATISATION</h3>
      <ul>
        <li>Climatiseur en gainable</li>
        <li>Climatiseur en cassette</li>
        <li>Climatiseur mono-split mural</li>
        <li>Climatiseur duo-split mural</li>
        <li>Climatiseur trio-split mural</li>
        <li>Climatiseur quatro-split mural</li>
      </ul>
    </div>
    <div class="col-sm">
      <h3>CHAUFFAGE</h3>
      <ul>
        <li>Chaudière à gaz murale</li>
        <li>Radiateur électrique</li>
        <li>Radiateur à eau</li>
        <li>Plancher chauffant</li>
      </ul>
    </div>
    <div class="col-sm">
      <h3>VMC</h3>
      <ul>
        <li>Pose aspiration VMC</li>
        <li>Remplacement aspiration VMC</li>
      </ul>
    </div>
  </div>
</div>
<!-- QUOTATION -->
<p>Now is <%= Time.now %><p>

<!-- APPOINTEMENT -->
<div class="appointement">
  <form action="devis">
    <p>Mettez l'adresse du  job</p>
    <input type="text">
    <p>case coché job</p>
    <input type="text">
    <p>prix materiel</p>
    <input type="text">
    <p>total</p>
    <p>€€€€€</p>
  </form>
</div>

app/views/pages/home.html.erb
<!-- LANDING -->
<div class="container-head">
  <h1>AR PLOMBERIE CLIMATISATION CHAUFFAGE</h1>
  <h4>"Enfin un plombier en qui<br> je peux avoir confiance"</h4>
  <div class="btn-home">
    <button id="btn-devis"><%= link_to 'DEVIS',appointements_path %></button>
    <button id="btn-rdv"><%= link_to 'RENDEZ-VOUS',appointements_path %></button>
    <button id="btn-contact"><%= link_to 'CONTACT',appointements_path %></button>
  </div>
</div>


<!-- CONTACT -->

<div class="container-contact">
  <h2>Contactez moi</h2>
  <ul>
    <li>
      <h5>Email</h5>
      <p>Si vous souhaitez prendre rendez-vous,<br> ou pour toutes questions subsidiaires.</p>
    </li>

    <li>
      <h5>Telephone</h5>
      <p>Si vous souhaitez prendre rendez-vous, <br>ou pour toutes questions subsidiaires.</p>
    </li>

    <li>
      <h5>Messenger</h5>
      <p>Si vous souhaitez prendre rendez-vous,<br> ou pour toutes questions subsidiaires.</p>
    </li>
  </ul>
</div>

app/views/shared/_flashes.html.erb
    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h5>wazzza</h5>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Mes Options", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Devis gratuit", "#", class: "dropdown-item" %>
            <%= link_to "Rendez-vous", "#", class: "dropdown-item" %>
            <%= link_to "Contactez moi", "#", class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connection", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>